.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.travis.yml
Pipfile
Pipfile.lock
setup.cfg
timetracker/timetracker/settings.py
timetracker/vms/models.py

The code is linted on every push with Travis CI.

Set up linting with flake8

---

timetracker/account/models.py
timetracker/account/test/models/test_user_model.py
timetracker/timetracker/settings.py
timetracker/vms/models.py
timetracker/vms/test/conftest.py
timetracker/vms/test/models/test_time_record_model.py

This uncovered a few bugs in our log messages, so those are fixed as well.

Add logging configuration.

---

timetracker/vms/models.py
timetracker/vms/test/models/test_time_record_model.py

Time tracker strings are more friendly.

Datechecks

---

.idea/codeStyles/codeStyleConfig.xml
Pipfile
Pipfile.lock
timetracker/account/templates/registration/login.html
timetracker/templates/bootstrap4/errors.html
timetracker/timetracker/settings.py

Use `django-crispy-forms` to improve the styling of the login form.
Closes #17

Style login form

---

timetracker/account/forms.py
timetracker/account/templates/registration/signup.html
timetracker/account/urls.py
timetracker/account/views.py
timetracker/timetracker/urls.py

can sign up. redirects to profile
closes #6

Added user signup view.

---

timetracker/vms/admin.py
timetracker/vms/migrations/0007_clientid.py
timetracker/vms/models.py

Make client IDs non-editable in the admin.

---

timetracker/account/test/views/test_sign_up_view.py
timetracker/account/urls.py
timetracker/account/views.py
timetracker/conftest.py
timetracker/timetracker/urls.py

Our timezone middleware has changed so that our custom login logic was no longer required. Also added a test case for signing up.

Clean up account views.

---

timetracker/vms/forms.py
timetracker/vms/templates/vms/dashboard.html

small changes to include task in clocking in

---

timetracker/vms/forms.py
timetracker/vms/test/conftest.py
timetracker/vms/test/forms/test_clock_in_form.py

Prevent inactive employees from clocking in

---

timetracker/vms/models.py
timetracker/vms/templates/vms/dashboard.html
timetracker/vms/templates/vms/employee-dash.html
timetracker/vms/test/models/test_employee_model.py
timetracker/vms/urls.py
timetracker/vms/views.py

moved employee-dash into its own place.  Cleared up dashboard. added absolute url for employees
closes #45

Changes dashboard and creates employee dashboard page

---

timetracker/vms/templates/vms/clientview.html
timetracker/vms/urls.py
timetracker/vms/views.py

Added Client View with their name and info

Added Client View with their name and info

---

timetracker/timetracker/settings.py
timetracker/vms/models.py
timetracker/vms/templates/vms/client-job-detail.html
timetracker/vms/templates/vms/client-job-list.html
timetracker/vms/templates/vms/clientview.html
timetracker/vms/test/views/test_client_job_detail_view.py
timetracker/vms/test/views/test_client_job_list_view.py
timetracker/vms/urls.py
timetracker/vms/views.py

Client administrators can list and update jobs.
Closes #55

Add views for managing client jobs

---

timetracker/vms/forms.py
timetracker/vms/models.py
timetracker/vms/templates/vms/unapproved-hours-list.html
timetracker/vms/test/forms/test_time_record_approval_form.py
timetracker/vms/test/views/test_time_record_approve_view.py
timetracker/vms/test/views/test_unapproved_time_record_list_view.py
timetracker/vms/urls.py
timetracker/vms/views.py

Supervisors at client companies can view a list of unapproved hours and approve them.
Closes #54

Add views for approving hours

---

.travis.yml
Pipfile.lock
timetracker/vms/forms.py

Also modified the CI script to install the package versions in our Pipfile.lock rather than the most recent version so that this issue doesn't randomly occur in the future.
Fixes #72

Fix linting errors

---

timetracker/vms/models.py
timetracker/vms/templates/vms/employee-dash.html
timetracker/vms/templatetags/time_record_tags.py
timetracker/vms/test/models/test_time_record_model.py

Employee pay rate

---

timetracker/vms/models.py
timetracker/vms/templates/vms/staffing-agency-employee.html
timetracker/vms/templates/vms/staffing-agency.html
timetracker/vms/urls.py
timetracker/vms/views.py

added staffing agency view and view framework for specific employee.

---

timetracker/vms/forms.py
timetracker/vms/models.py
timetracker/vms/templates/vms/staffing-agency-employee-apply.html
timetracker/vms/templates/vms/staffing-agency-employee.html
timetracker/vms/urls.py
timetracker/vms/views.py

Add interface to apply employees to clients.

---

timetracker/vms/managers.py
timetracker/vms/test/models/test_time_record_model.py

Fix issue with total_time and no records

---

timetracker/vms/forms.py
timetracker/vms/models.py
timetracker/vms/templates/vms/employee-approval.html
timetracker/vms/templates/vms/employee-pending.html
timetracker/vms/urls.py
timetracker/vms/views.py

showing the employee pending and approval

showing the employee pending and approval

---

timetracker/vms/templates/vms/dashboard.html
timetracker/vms/views.py

updated dashboard with conditional display of client and staffing agency pages. Includes links to those pages.
Only displays portions of the page if the user is recognized as that entity.

Dashboard Update

---

timetracker/vms/forms.py
timetracker/vms/templates/vms/client-job-create.html
timetracker/vms/templates/vms/client-job-list.html
timetracker/vms/urls.py
timetracker/vms/views.py

added create job page off of the job list page.

---

.idea/misc.xml
timetracker/vms/forms.py
timetracker/vms/models.py
timetracker/vms/templates/vms/client-detail.html
timetracker/vms/templates/vms/dashboard.html
timetracker/vms/templates/vms/staffing-agency-apply.html
timetracker/vms/templates/vms/staffing-agency-employee-pending.html
timetracker/vms/templates/vms/staffing-agency-employee.html
timetracker/vms/templates/vms/staffing-agency.html
timetracker/vms/urls.py
timetracker/vms/views.py

So it's not complete but here it is today.  Sorry for not pushing this earlier I was out and did not see the msg for pull request.  there will prob be merge conflicts with master but for now here it is to review.   
Still needs:
-needs to allow approving as staff admin.
-adding client admins.  
-haven't ran flake8 yet so I will fix that when I fix the merge conflicts

applying to staff.   staff view with approved and unapproved list

---

timetracker/vms/templates/vms/clock-in.html
timetracker/vms/templates/vms/employee-detail.html

Display client and employee IDs on employee detail and clock in pages.

Add ID information to pages.

---

timetracker/vms/test/views/test_employee_detail_view.py

added get test for client admin on employee-detail-view

---

timetracker/templates/base.html
timetracker/vms/templates/vms/employee-detail.html
timetracker/vms/test/views/test_employee_detail_view.py
timetracker/vms/views.py

Added time record range selectors to the employee detail view

---

timetracker/vms/mixins.py
timetracker/vms/templates/vms/employee-detail.html
timetracker/vms/test/mixins/test_date_range_mixin.py
timetracker/vms/views.py

This will allow us to use the functionality from the date filtering in the employee detail view for other views.

Add mixin to handle filtering by date

---

timetracker/vms/templates/vms/staffing-agency-employee.html

Replaced the link to the approval page with a form that submits a POST request to the approval endpoint.
Fixes #101

Fix issue approving staffing agency employees.
